#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift "#{__dir__}/../../../lib"
require "dry/cli"

module ColorsDemo
  extend Dry::CLI::Registry

  class Print < Dry::CLI::Command
    desc "Demonstrate all available colors"

    # rubocop:disable Metrics/AbcSize
    def call
      demo = <<~DEMO
        # Style ###############################################################
        Bold: #{bold("This is bold")}
        # Foreground ##########################################################
        Black:   #{black("This is black")}
        Red:     #{red("This is red")}
        Green:   #{green("This is green")}
        Yellow:  #{yellow("This is yellow")}
        Blue:    #{blue("This is blue")}
        Magenta: #{magenta("This is magenta")}
        Cyan:    #{cyan("This is cyan")}
        White:   #{white("This is white")}
        # Background ##########################################################
        Black:   #{on_black("This is black")}
        Red:     #{on_red("This is red")}
        Green:   #{on_green("This is green")}
        Yellow:  #{on_yellow("This is yellow")}
        Blue:    #{on_blue("This is blue")}
        Magenta: #{on_magenta("This is magenta")}
        Cyan:    #{on_cyan("This is cyan")}
        White:   #{on_white("This is white")}
        # Combinations ########################################################
        Bold+Foreground:            #{bold(red("This is bold red"))}
        Bold+Background:            #{bold(on_green("This is bold on green"))}
        Bold+Foreground+Background: #{bold(red(on_green("This is bold red on green")))}
      DEMO
      puts demo
    end
    # rubocop:enable Metrics/AbcSize
  end

  register "print", Print
end

Dry.CLI(ColorsDemo).call
