#!/usr/bin/env ruby
$:.unshift __dir__ + '/../../lib'
require 'hanami/cli'

module Foo
  module CLI
    include Hanami::Cli

    class Hi
      def call
        puts "world"
      end
    end

    class Version
      def call
        puts "1.0.0"
      end
    end

    register 'hello',   Hi
    register 'version', Version
  end
end

module Webpack
  module Commands
    include Hanami::Cli

    class Version
      def call
        puts "1.0.0 yay!"
      end
    end

    register 'version', Version
  end
end

Foo::CLI.call
