#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path("#{__dir__}/../../../lib")
require "dry/cli"
require_relative "../../../lib/dry/cli/command"
require "json"
require "dry/types"

Types = Dry.Types()

module WithDryTypes
  extend Dry::CLI::Registry

  class Info < Dry::CLI::Command
    desc "Display info"

    argument :type, desc: "Type of the information", required: true
    argument :lines, desc: "Number of lines to show", cast: Types::Coercible::Integer.default(5), default: 10
    option :sudo_mode, desc: "Enable sudo mode?", cast: Types::Params::Bool, default: false
    option :uid, desc: "UID of the user to run as", cast: ->(v) { v.to_i }
    option :flags, cast: ->(f) { f.reverse }, type: :array

    def call(**options)
      puts JSON.dump(options)
    end
  end

  class Tags < Dry::CLI::Command
    desc "Display tags"

    argument :tags, desc: "Tags to display", type: :array, cast: ->(t) { t.upcase }

    def call(**options)
      puts JSON.dump(options)
    end
  end

  register "info", Info
  register "tags", Tags
end

Dry.CLI(WithDryTypes).call
