#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path("#{__dir__}/../../../lib")
require "dry/cli"
require_relative "../../../lib/dry/cli/command"
require "json"

if ENV["DONT_LOAD_EXTENSION"]
  require "dry/types"
else
  Dry::CLI.load_extensions(:dry_types)
end

Types = Dry.Types()

module WithDryTypes
  extend Dry::CLI::Registry

  class Info < Dry::CLI::Command
    desc "Display info"

    argument :type, desc: "Type of the information", required: true
    argument :lines, desc: "Number of lines to show", type: Types::Coercible::Integer, default: 10
    option :sudo_mode, desc: "Enable sudo mode?", type: Types::Params::Bool, default: false

    def call(**options)
      puts JSON.dump(options)
    end
  end

  register "info", Info
end

Dry.CLI(WithDryTypes).call
